### ISSUE TITLE
Can't launch games

### ISSUE THREAD

**Issue by currall** [Countryen/gog-generic-integration#1]
How can I make the plugin launch games? The only option is a greyed out install button

**Comment by Countryen** [comment]
Hey @currall.

Sorry, that is not possible currently. The plugin just adds the game as a placeholder to the library so that you can see "you have it already somewhere in your possession".

To launch them you'd need to install them and add them to Galaxy the usual way.

I also forgot that this repository is still public and not private - this might change soon.
I have not maintained the project in a long time (2 years) and cannot say what works / doesn't work right now.

If you want I can have a look into the code and try to update it and see if I can make this work for you.
But: Where would you expect Galaxy to look for the game? Do you intend to provide the installation-path (to an EXE file) inside the CSV file? The plugin needs to know where/what to start (if possible).

**Comment by currall** [comment]
Thanks for the reply. I figured that it wasn't part of the plugin but just wanted to make sure I wasnt missing anything. I will probably modify it to launch games at some point
